FROM ubuntu:14.04
MAINTAINER neil@grogan.ie

ENV DIRPATH /data
# TODO!!!
#ENV INSTALL_PKGS 

#RUN sudo apt-get update && \
#         sudo apt-get install -y $INSTALL_PKGS

WORKDIR $DIRPATH

VOLUME $DIRPATH

CMD ["/bin/bash"]